// SPDX-License-Identifier: AGPL-3.0-only
// AUTO-GENERATED by scripts/build.py's _generate_search_keywords() from
// data/tools-config.json's `keywords` field — never edit by hand, this
// exact file gets overwritten with real content on every build. This
// checked-in copy is just the placeholder shape so an unbuilt source tree
// still has a valid file at this path (same convention as sw.js's
// checked-in template with __PLACEHOLDER__ tokens).
window.PDFREE_SEO_KEYWORDS = {};
