name = "pdfree33"
compatibility_date = "2026-05-07"
main = "src/index.js"

[placement]
mode = "smart"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "404-page"
run_worker_first = true

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "pdfree_events"
