#!/usr/bin/env python3
"""
SSG build script for PDFree.

Generates all 60 tool pages from templates + data, then copies static assets
into dist/. One command produces a deployable directory.

Usage:
    python3 scripts/build.py           — full build into dist/
    python3 scripts/build.py --check   — dry run (render only, no write)

Output: dist/
  ├── {tool-slug}/index.html           (12 EN tool pages)
  ├── {lang}/{tool-slug}/index.html    (48 DE/ES/FR/PT tool pages)
  ├── index.html  de/ es/ fr/ pt/      (homepages, copied as-is)
  ├── css/ js/ fonts/ icons/           (static assets)
  ├── manifest.json  sw.js  favicon.ico
  └── sitemap.xml                      (auto-generated)
"""
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
from datetime import date

try:
    from jinja2 import Environment, FileSystemLoader, select_autoescape
except ImportError:
    print('ERROR: jinja2 not installed. Run: pip3 install jinja2', file=sys.stderr)
    sys.exit(1)

ROOT      = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIST      = os.path.join(ROOT, 'dist')
DATA      = os.path.join(ROOT, 'data')
TEMPLATES = os.path.join(ROOT, 'scripts', 'templates')
CONFIG    = os.path.join(DATA, 'tools-config.json')
CONTENT   = os.path.join(DATA, 'content')

BASE_URL = 'https://pdfree.io'

# Dirs/files to skip when copying root → dist
SKIP_DIRS = {
    '.git', 'node_modules', '.wrangler', '.claude', '.husky',
    'dist', 'data', 'scripts',
    # Old slug — redirect handled in _redirects, no HTML needed in dist
    'annotate',
    # Internal research files — never serve publicly
    'research',
}
SKIP_FILES = {
    'wrangler.toml', 'wrangler.jsonc', 'wrangler.json',  # deployment configs — never serve as static
    '.assetsignore', 'eslint.config.js',
    'package-lock.json', '.gitignore', 'vercel.json',
    'CONTRIBUTING.md', 'LICENSE', 'README.md',
    '3c51839cdd6944c79259fdf6a0c383cc.txt',
    'qpdf-run-0.2.1.tgz',
    'seo-content.html',   # legacy dev artifact — content now lives in data/content/
    'test-dedup.pdf',      # test fixture — not a public asset
    'index.template.html',   # build template — not a user-facing page
    'sitemap.xml',           # generated by build.py — root copy is stale, dist/ version is authoritative
}
SKIP_EXTS = {'.py', '.toml', '.local'}


# ── Asset hashing ────────────────────────────────────────────────────────────

def _md5_short(path, length=8):
    """Return first N chars of MD5 hash of file content."""
    if not os.path.exists(path):
        return 'missing'
    with open(path, 'rb') as f:
        return hashlib.md5(f.read()).hexdigest()[:length]


def _compute_hashes():
    app_hash = _md5_short(os.path.join(ROOT, 'js', 'app.js'))
    # cache_version hashes ALL js/*.js + css/*.css files + sw.js + the static
    # homepage shells + the tool-page template so the SW cache is busted
    # whenever any of these change — not just app.js. Previously only
    # app.js+sw.js were hashed, so changes to processor.js, pdf2wordTables.js
    # etc. kept the same cache_version → SW served stale files. CSS was added
    # for the identical reason: a CSS-only deploy left cache_version
    # unchanged, so the SW's cache-first strategy served already-visited
    # users stale CSS indefinitely. HTML shells were added after the same bug
    # hit an HTML-only fix (CSP script-src in index.html /
    # scripts/templates/tool-page.html): cache_version stayed unchanged, so
    # already-visited/installed users' SW never reinstalled and kept serving
    # the old cached HTML — self-healing only after a 2nd navigation via
    # stale-while-revalidate — instead of getting the immediate reload/
    # update-banner that JS/CSS changes trigger.
    combined = b''
    js_dir = os.path.join(ROOT, 'js')
    for fname in sorted(os.listdir(js_dir)):
        if fname.endswith('.js') and fname != 'vendor':
            fpath = os.path.join(js_dir, fname)
            if os.path.isfile(fpath):
                with open(fpath, 'rb') as f:
                    combined += f.read()
    css_dir = os.path.join(ROOT, 'css')
    for fname in sorted(os.listdir(css_dir)):
        if fname.endswith('.css'):
            fpath = os.path.join(css_dir, fname)
            if os.path.isfile(fpath):
                with open(fpath, 'rb') as f:
                    combined += f.read()
    sw_path = os.path.join(ROOT, 'sw.js')
    if os.path.exists(sw_path):
        with open(sw_path, 'rb') as f:
            combined += f.read()
    html_shells = [
        'index.html', 'de/index.html', 'es/index.html', 'fr/index.html', 'pt/index.html',
        os.path.join('scripts', 'templates', 'tool-page.html'),
    ]
    for rel in html_shells:
        fpath = os.path.join(ROOT, rel)
        if os.path.isfile(fpath):
            with open(fpath, 'rb') as f:
                combined += f.read()
    cache_version = hashlib.md5(combined).hexdigest()[:8]
    return {
        'app':            app_hash,
        'cache_version':  cache_version,
        'worker':         _md5_short(os.path.join(ROOT, 'js', 'worker.js')),
        'components_css': _md5_short(os.path.join(ROOT, 'css', 'components.css')),
        'css':            cache_version,  # same combined hash busts all CSS at once
    }


# ── Nav items ────────────────────────────────────────────────────────────────

# Tools that appear in the nav bar, in display order.
# draw, compare have no locale slugs → appended manually with absolute EN paths.
# pdf2word is in this list because it has locale slugs in tools-config.
# pdf2excel is EN-only for now — falls back to the absolute EN path on every
# other language, same mechanism already used for draw/compare.
_NAV_TOOL_IDS = [
    'merge', 'split', 'compress', 'jpg2pdf', 'pdf2jpg',
    'watermark', 'pagenum', 'metadata', 'extract',
    # draw-on-pdf inserted here (EN-only, no locale slugs)
    'rotate', 'protect', 'pdf2word', 'pdf2excel', 'pdf2ppt', 'pdf2md', 'unlock',
]

def _build_nav_items(lang, all_tools):
    """Return list of {href, label, tool_key} for the top nav bar.

    hrefs use '../slug/' which resolves correctly from any tool page:
      EN depth-1  /merge-pdf/        →  ../split-pdf/  =  /split-pdf/      ✓
      PT depth-2  /pt/extrair-pdf/   →  ../juntar-pdf/ =  /pt/juntar-pdf/  ✓
    Specialty pages without locale slugs (draw, compare) use absolute EN paths.
    """
    tool_map = {t['id']: t for t in all_tools}
    items = []
    for tool_id in _NAV_TOOL_IDS:
        t = tool_map.get(tool_id)
        if not t:
            continue
        slug  = t['slugs'].get(lang)
        label = t['navLabels'].get(lang, t['navLabels']['en'])
        # If no locale slug exists, point to absolute EN path (avoids /ru/metadata-pdf/ dead URLs)
        href  = f'../{slug}/' if slug is not None else f'/{t["slugs"]["en"]}/'
        items.append({'href': href, 'label': label, 'tool_key': t['toolKey']})
        if tool_id == 'extract':
            # Draw: use locale slug when available, fall back to EN
            _draw_slugs = {'en': 'draw-on-pdf', 'de': 'de/pdf-zeichnen', 'es': 'es/dibujar-en-pdf', 'fr': 'fr/dessiner-sur-pdf', 'pt': 'pt/desenhar-no-pdf'}
            _draw_labels = {'en': 'Draw', 'de': 'Zeichnen', 'es': 'Dibujar', 'fr': 'Dessiner', 'pt': 'Desenhar'}
            _draw_slug = _draw_slugs.get(lang, _draw_slugs['en'])
            _draw_href = f'../{_draw_slug}/' if lang != 'en' else f'/{_draw_slug}/'
            items.append({'href': _draw_href, 'label': _draw_labels.get(lang, 'Draw'), 'tool_key': 'draw-pdf'})
    # Compare — EN-only, no locale slugs
    items.append({'href': '/compare-pdf/', 'label': 'Compare', 'tool_key': 'compare'})
    return items


# ── Hreflang ─────────────────────────────────────────────────────────────────

def _hreflang_links(tool, config):
    """Return list of (lang_code, absolute_url) for all languages."""
    links = []
    for lang_code, lang_cfg in config['languages'].items():
        slug = tool['slugs'].get(lang_code)
        if not slug:
            continue
        if lang_code == 'en':
            url = f"{BASE_URL}/{slug}/"
        else:
            url = f"{BASE_URL}/{lang_cfg['dir']}/{slug}/"
        links.append((lang_code, url))
    return links


# ── Schema builders ───────────────────────────────────────────────────────────

def _webapp_schema(tool, lang, canonical_path):
    return json.dumps({
        "@context": "https://schema.org",
        "@type": "SoftwareApplication",
        "name": tool['breadcrumb'][lang],
        "description": tool['metaDescs'].get(lang, tool['descs'][lang]),
        "url": f"{BASE_URL}/{canonical_path}",
        "applicationCategory": "UtilityApplication",
        "operatingSystem": "Web, iOS, Android",
        "browserRequirements": "Requires a modern browser with JavaScript and WebAssembly enabled",
        "inLanguage": lang,
        "isAccessibleForFree": True,
        "offers": {
            "@type": "Offer",
            "price": "0",
            "priceCurrency": "USD",
            "availability": "https://schema.org/InStock",
        },
        "featureList": [
            "No file upload required — 100% client-side processing",
            "100% private — files never leave your device",
            "No account or signup needed",
            "No artificial file size limits — processes locally in your browser",
            "Works offline after first visit",
            "Free forever — no subscription",
        ],
        "softwareVersion": "6.2",
        "datePublished": "2023-01-01",
        "downloadUrl": f"{BASE_URL}/{canonical_path}",
        "screenshot": {
            "@type": "ImageObject",
            "url": "https://pdfree.io/icons/og-image.jpg",
            "width": 1200,
            "height": 633,
        },
        "softwareHelp": {"@type": "CreativeWork", "url": "https://pdfree.io/"},
        "provider": {"@type": "Organization", "name": "PDFree", "url": "https://pdfree.io"},
    }, indent=2, ensure_ascii=False)


def _faq_schema(faq_items):
    return json.dumps({
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": faq_items,
    }, indent=2, ensure_ascii=False)


def _breadcrumb_schema(tool, lang, lang_cfg, canonical_path):
    items = [{"@type": "ListItem", "position": 1, "name": "PDFree", "item": "https://pdfree.io/"}]
    if lang != 'en':
        items.append({
            "@type": "ListItem", "position": 2,
            "name": lang_cfg['code'].upper(),
            "item": f"{BASE_URL}/{lang_cfg['dir']}/",
        })
        items.append({
            "@type": "ListItem", "position": 3,
            "name": tool['breadcrumb'][lang],
            "item": f"{BASE_URL}/{canonical_path}",
        })
    else:
        items.append({
            "@type": "ListItem", "position": 2,
            "name": tool['breadcrumb'][lang],
            "item": f"{BASE_URL}/{canonical_path}",
        })
    return json.dumps({
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": items,
    }, indent=2, ensure_ascii=False)


# ── Content loading ───────────────────────────────────────────────────────────

def _load_content(tool_id, lang):
    """Load seo HTML + FAQ items + HowTo schema for one tool/language pair."""
    seo_path   = os.path.join(CONTENT, lang, f'{tool_id}.html')
    faq_path   = os.path.join(CONTENT, lang, f'{tool_id}-faq.json')
    howto_path = os.path.join(CONTENT, lang, f'{tool_id}-howto.json')

    seo_html = ''
    if os.path.exists(seo_path):
        seo_html = open(seo_path, encoding='utf-8').read().strip()

    faq_items = []
    if os.path.exists(faq_path):
        faq_items = json.load(open(faq_path, encoding='utf-8'))

    howto_schema = None
    if os.path.exists(howto_path):
        howto_schema = open(howto_path, encoding='utf-8').read().strip()

    return seo_html, faq_items, howto_schema


# ── Version manifest ─────────────────────────────────────────────────────────

def _git_short_hash():
    """Return short git commit hash of HEAD. Falls back to 'unknown'."""
    try:
        return subprocess.check_output(
            ['git', 'rev-parse', '--short', 'HEAD'],
            cwd=ROOT,
            stderr=subprocess.DEVNULL,
        ).decode().strip()
    except Exception:
        return 'unknown'


def _write_version_json(hashes, dist):
    """Write dist/version.json so smoke_prod.sh can verify production == local."""
    from datetime import datetime, timezone
    data = {
        'version':       _git_short_hash(),
        'date':          datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'),
        'cache_version': hashes['cache_version'],
    }
    out = os.path.join(dist, 'version.json')
    with open(out, 'w') as f:
        json.dump(data, f)
    print(f'  version.json  ({data["version"]})')


# ── Sitemap ───────────────────────────────────────────────────────────────────

def _git_lastmod(rel_path):
    """Return YYYY-MM-DD of the last git commit that touched rel_path.
    Falls back to today if the file has no git history (new/untracked)."""
    try:
        out = subprocess.check_output(
            ['git', 'log', '-1', '--format=%cI', '--', rel_path],
            cwd=ROOT,
            stderr=subprocess.DEVNULL,
        ).decode().strip()
        if out:
            return out[:10]
    except Exception:
        pass
    return date.today().isoformat()


# Locales that have a real homepage file (index.html at their dir root).
# The other languages in config['languages'] (id/vi/ru/ja/it/ko/nl/pl/tr) only
# have individual tool pages — no {dir}/index.html exists for them. Cloudflare
# Workers Assets is configured with not_found_handling = "single-page-application"
# (wrangler.toml), so a request to e.g. /ru/ 200s with the EN homepage's HTML
# instead of a real 404 — including its self-canonical pointing at
# https://pdfree.io/. Submitting /ru/ in the sitemap with hreflang="ru" tells
# Google "here is Russian content" while the page itself tells Google "actually
# I'm a duplicate of the English homepage" — Google resolves that by folding
# /ru/ into the EN canonical, which is exactly what Search Console reports as
# "Alternate page with proper canonical tag". Their tool sub-pages (e.g.
# /ru/objedinit-pdf/) are real files and unaffected — only the homepage-level
# entries need to stay out of the sitemap/hreflang set.
HOMEPAGE_LANGS = {'en', 'de', 'es', 'fr', 'pt', 'id'}

# Native display names for the language switcher.
LANG_NAMES = {
    'en': 'English', 'es': 'Español', 'pt': 'Português', 'de': 'Deutsch',
    'fr': 'Français', 'id': 'Bahasa Indonesia', 'vi': 'Tiếng Việt',
    'ru': 'Русский', 'ja': '日本語', 'it': 'Italiano', 'ko': '한국어',
    'nl': 'Nederlands', 'pl': 'Polski', 'tr': 'Türkçe',
}

SPECIALTY_PAGES = [
    'annotate-pdf',
    # highlight-pdf and sign are noindex,nofollow (doorway content referencing
    # a non-existent annotation UI — see commit 8178b68) — excluded from the
    # sitemap so we don't submit a page for indexing that tells Google not to
    # index it. Re-add once their copy is rewritten around a real tool and the
    # noindex tag is removed.
    'hipaa-pdf-tools',
    'ilovepdf-alternative',
    'compress-large-pdf-free',
    'secure-pdf-tools',
    # compare-pdf is EN-only so stays here; ocr-pdf/pdf-to-word/draw-on-pdf
    # are handled by _lang_specialty below (with full locale alternates).
    'compare-pdf',
    # pdf-to-word-free is EN-only (no locale variants)
    'pdf-to-word-free',
    # Specific-intent landing pages
    'compress-pdf-for-email',
    'split-pdf-into-multiple-files',
    'split-large-pdf',
    # split-pdf-every-page and split-pdf-free-no-watermark were redirected
    # into /split-pdf/ (301s in _redirects) — both had near-zero organic
    # visibility (GSC: 0-1 impressions/3mo) and were pure marketing-angle
    # duplicates of the hub; their unique content (ZIP naming, watermark FAQ)
    # was merged into data/content/en/split.html instead of left orphaned.
    'split-pdf-by-range',
    'split-pdf-odd-even',
    'merge-pdf-files-into-one',
    'merge-large-pdf-files',
    'merge-pdf-without-uploading',
    'merge-password-protected-pdf',
    'merge-scanned-pdf',
    'pdf-to-jpg-300-dpi',
    'pdf-to-jpg-high-quality',
    'pdf-to-png',
    'extract-text-from-scanned-pdf',
    'make-scanned-pdf-searchable',
    'ocr-pdf-no-upload',
    'pdf-compression-glossary',
    # No-upload hub page
    'pdf-tools-no-upload',
    # Competitor alternative pages
    'smallpdf-alternative',
    'pdf24-alternative',
    'adobe-acrobat-alternative',
    # Stage 5 long-tail landing pages
    'merge-pdf-no-size-limit',
    'free-pdf-tools-no-signup',
    'compress-pdf-without-account',
    'convert-pdf-to-jpg-free-no-watermark',
    'rotate-pdf-free-permanently',
    # Audience landing pages
    'free-pdf-tools',
    'for-accountants',
    'for-lawyers',
    'for-students',
    'for-teachers',
    # Research / benchmark project page (EN-only for now)
    'atlas',
    # Static pages
    'privacy.html',
    'terms.html',
    # Blog index + Blog posts
    'blog',
    'blog/how-to-annotate-pdf-on-mobile',
    'blog/how-to-fill-pdf-form',
    'blog/how-to-sign-pdf-free',
    'blog/how-to-compress-pdf-for-email',
    'blog/how-to-split-a-pdf',
    'blog/how-to-remove-watermark-from-pdf',
    'blog/how-to-merge-pdf-files-for-free',
    'blog/how-to-password-protect-a-pdf',
    'blog/how-to-remove-pdf-password',
    'blog/how-to-compress-pdf-without-losing-quality',
    'blog/how-to-rotate-pdf-pages',
    'blog/free-pdf-tools-without-daily-limits',
    'blog/how-to-convert-pdf-to-jpg',
    'blog/how-to-add-watermark-to-pdf',
    'blog/how-to-extract-pages-from-pdf',
    'blog/merge-pdf-offline',
    'blog/how-to-fill-pdf-with-signature',
]

# NOTE (Sitemap Index): If the site ever grows beyond 50,000 URLs, split the sitemap
# into multiple files (e.g. sitemap-tools.xml, sitemap-blog.xml) and serve a
# sitemap index at /sitemap.xml that references them. The Google limit is 50,000
# URLs or 50 MB per sitemap file. Current URL count is well below this threshold.


def _write_sitemap(config, out_dir):
    """Generate sitemap.xml with hreflang alternate links for all languages.
    lastmod reflects the last git commit date so Google only re-crawls changed pages."""

    langs = config['languages']  # ordered: en first
    lang_codes = list(langs.keys())

    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
        '        xmlns:xhtml="http://www.w3.org/1999/xhtml">',
    ]

    def _url_block(loc, lastmod, alternates, priority=None, changefreq=None):
        """alternates: list of (hreflang, href)"""
        block = ['  <url>',
                 f'    <loc>{loc}</loc>',
                 f'    <lastmod>{lastmod}</lastmod>']
        if changefreq:
            block.append(f'    <changefreq>{changefreq}</changefreq>')
        if priority:
            block.append(f'    <priority>{priority}</priority>')
        for lang, href in alternates:
            block.append(f'    <xhtml:link rel="alternate" hreflang="{lang}" href="{href}"/>')
        block.append('  </url>')
        return block

    # ── Homepages ──────────────────────────────────────────────
    # Only locales in HOMEPAGE_LANGS have a real homepage file — see the
    # comment on HOMEPAGE_LANGS for why the rest must not appear here.
    homepage_alts = [(lc if lc != 'en' else 'en', f"{BASE_URL}/{cfg['dir']}/" if lc != 'en' else f"{BASE_URL}/")
                     for lc, cfg in langs.items() if lc in HOMEPAGE_LANGS]
    homepage_alts.append(('x-default', f'{BASE_URL}/'))
    lines += _url_block(f'{BASE_URL}/', _git_lastmod('index.html'), homepage_alts, priority='1.0', changefreq='weekly')

    # ── Language sub-homepages ─────────────────────────────────
    for lc, cfg in langs.items():
        if lc == 'en' or lc not in HOMEPAGE_LANGS:
            continue  # already emitted above, or has no real homepage file
        lang_url = f"{BASE_URL}/{cfg['dir']}/"
        lines += _url_block(lang_url, _git_lastmod(f"{cfg['dir']}/index.html"), homepage_alts, priority='0.9', changefreq='weekly')

    # ── Tool pages — one <url> per language variant ────────────
    for tool in config['tools']:
        en_slug = tool['slugs'].get('en')
        if not en_slug:
            continue
        en_url = f"{BASE_URL}/{en_slug}/"
        lastmod = _git_lastmod(f"data/content/en/{tool['id']}.html")

        # Build the full alternates list (all locales)
        alts = []
        for lc, cfg in langs.items():
            slug = tool['slugs'].get(lc)
            if not slug:
                continue
            href = f"{BASE_URL}/{slug}/" if lc == 'en' else f"{BASE_URL}/{cfg['dir']}/{slug}/"
            alts.append((lc, href))
        alts.append(('x-default', en_url))

        # Emit a separate <url> block for every language variant so that
        # Googlebot crawls and indexes each localised URL individually.
        for lc, cfg in langs.items():
            slug = tool['slugs'].get(lc)
            if not slug:
                continue
            loc = f"{BASE_URL}/{slug}/" if lc == 'en' else f"{BASE_URL}/{cfg['dir']}/{slug}/"
            lmod = lastmod if lc == 'en' else _git_lastmod(f"data/content/{lc}/{tool['id']}.html")
            lines += _url_block(loc, lmod, alts, priority='0.8', changefreq='weekly')

    # ── Specialty / SEO pages ──────────────────────────────────
    # Localized alternates for the 3 specific-intent landing pages
    _localized_specialty = {
        'compress-pdf-for-email': {
            'de': 'de/pdf-fuer-email-komprimieren',
            'fr': 'fr/compresser-pdf-pour-email',
            'es': 'es/comprimir-pdf-para-email',
            'pt': 'pt/comprimir-pdf-para-email',
        },
        'split-pdf-into-multiple-files': {
            'de': 'de/pdf-aufteilen-mehrere-dateien',
            'fr': 'fr/diviser-pdf-plusieurs-fichiers',
            'es': 'es/dividir-pdf-en-varios-archivos',
            'pt': 'pt/dividir-pdf-em-varios-arquivos',
        },
        'merge-pdf-files-into-one': {
            'de': 'de/pdf-dateien-zusammenfuehren',
            'fr': 'fr/fusionner-pdfs-en-un',
            'es': 'es/unir-pdfs-en-uno',
            'pt': 'pt/juntar-pdfs-em-um',
        },
    }

    for slug in SPECIALTY_PAGES:
        # .html files don't use trailing slashes; directories do
        if slug.endswith('.html'):
            url = f"{BASE_URL}/{slug}"
            lastmod_path = slug
        else:
            url = f"{BASE_URL}/{slug}/"
            lastmod_path = f"{slug}/index.html"
        loc_alts = _localized_specialty.get(slug)
        if loc_alts:
            alts = [('en', url)]
            for lc, loc_slug in loc_alts.items():
                alts.append((lc, f"{BASE_URL}/{loc_slug}/"))
            alts.append(('x-default', url))
        else:
            alts = [('en', url), ('x-default', url)]
        # Determine priority & changefreq by page type
        if slug.startswith('blog/'):
            _sp_priority, _sp_freq = '0.6', 'monthly'
        elif slug.endswith('.html'):
            _sp_priority, _sp_freq = '0.3', 'yearly'
        else:
            _sp_priority, _sp_freq = '0.7', 'monthly'
        lines += _url_block(url, _git_lastmod(lastmod_path), alts, priority=_sp_priority, changefreq=_sp_freq)

    # ── Localized specialty pages ──────────────────────────────
    for en_slug, loc_map in _localized_specialty.items():
        en_url = f"{BASE_URL}/{en_slug}/"
        for lc, loc_slug in loc_map.items():
            loc_url = f"{BASE_URL}/{loc_slug}/"
            # Build full alternates set (all locales + x-default)
            alts = [('en', en_url)]
            for lc2, ls2 in loc_map.items():
                alts.append((lc2, f"{BASE_URL}/{ls2}/"))
            alts.append(('x-default', en_url))
            lines += _url_block(loc_url, _git_lastmod(f"{loc_slug}/index.html"), alts)

    # ── Non-EN static specialty pages ──────────────────────────
    # Static specialty pages that exist in language subdirs but aren't
    # in tools-config (ocr, draw, pdf-to-word, flatten in each locale).
    # pdf-to-word EN is now in tools-config → its EN URL block comes from
    # the tools section above; skip EN here to avoid a duplicate sitemap entry.
    _lang_specialty = {
        'ocr-pdf': {
            'en': 'ocr-pdf',
            'de': 'de/ocr-pdf',
            'es': 'es/ocr-pdf',
            'fr': 'fr/ocr-pdf',
            'pt': 'pt/ocr-pdf',
        },
        'pdf-to-word': {
            'en': 'pdf-to-word',
            'de': 'de/pdf-zu-word',
            'es': 'es/pdf-a-word',
            'fr': 'fr/pdf-en-word',
            'pt': 'pt/pdf-para-word',
        },
        'draw-on-pdf': {
            'en': 'draw-on-pdf',
            'de': 'de/pdf-zeichnen',
            'es': 'es/dibujar-en-pdf',
            'fr': 'fr/dessiner-sur-pdf',
            'pt': 'pt/desenhar-no-pdf',
        },

    }
    # Tools fully migrated to SSG (all locales in tools-config) — all URL blocks
    # come from the tools loop above; skip the entire tool here to avoid duplicates.
    _ssg_fully_migrated = {'pdf-to-word'}

    for en_key, loc_map in _lang_specialty.items():
        if en_key in _ssg_fully_migrated:
            continue
        en_url = f"{BASE_URL}/{loc_map['en']}/"
        alts = [(lc, f"{BASE_URL}/{slug}/") for lc, slug in loc_map.items()]
        alts.append(('x-default', en_url))
        # Emit a URL block for each language variant
        for lc, slug in loc_map.items():
            loc_url = f"{BASE_URL}/{slug}/"
            lines += _url_block(loc_url, _git_lastmod(f"{slug}/index.html"), alts, priority='0.85', changefreq='monthly')

    # ── Non-EN blog index pages ──────────────────────────────
    _locale_blog_indexes = [
        {'lc': 'de', 'slug': 'de/blog', 'en_slug': 'blog'},
        {'lc': 'es', 'slug': 'es/blog', 'en_slug': 'blog'},
        {'lc': 'fr', 'slug': 'fr/blog', 'en_slug': 'blog'},
        {'lc': 'pt', 'slug': 'pt/blog', 'en_slug': 'blog'},
    ]
    for bi in _locale_blog_indexes:
        en_url = f"{BASE_URL}/{bi['en_slug']}/"
        loc_url = f"{BASE_URL}/{bi['slug']}/"
        alts = [('en', en_url), (bi['lc'], loc_url), ('x-default', en_url)]
        lines += _url_block(loc_url, _git_lastmod(f"{bi['slug']}/index.html"), alts, priority='0.5', changefreq='monthly')

    # ── Non-EN blog posts ─────────────────────────────────────
    # Blog posts translated/localized for DE, ES, FR, PT.
    # Each maps a language-slug to its EN counterpart for hreflang cross-referencing.
    _locale_blog_posts = [
        {
            'de': 'de/blog/pdf-zusammenfuehren-kostenlos',
            'en': 'blog/how-to-merge-pdf-files-for-free',
        },
        {
            'de': 'de/blog/pdf-verkleinern-ohne-qualitaetsverlust',
            'en': 'blog/how-to-compress-pdf-without-losing-quality',
        },
        {
            'es': 'es/blog/comprimir-pdf-sin-perder-calidad',
            'en': 'blog/how-to-compress-pdf-without-losing-quality',
        },
        {
            'es': 'es/blog/unir-archivos-pdf-gratis',
            'en': 'blog/how-to-merge-pdf-files-for-free',
        },
        {
            'fr': 'fr/blog/compresser-pdf-sans-perte-de-qualite',
            'en': 'blog/how-to-compress-pdf-without-losing-quality',
        },
        {
            'fr': 'fr/blog/fusionner-pdf-gratuitement',
            'en': 'blog/how-to-merge-pdf-files-for-free',
        },
        {
            'pt': 'pt/blog/comprimir-pdf-sem-perder-qualidade',
            'en': 'blog/how-to-compress-pdf-without-losing-quality',
        },
        {
            'pt': 'pt/blog/juntar-arquivos-pdf-gratis',
            'en': 'blog/how-to-merge-pdf-files-for-free',
        },
    ]
    for post_map in _locale_blog_posts:
        en_slug = post_map['en']
        en_url = f"{BASE_URL}/{en_slug}/"
        alts = [('en', en_url), ('x-default', en_url)]
        for lc, loc_slug in post_map.items():
            if lc == 'en':
                continue
            alts.append((lc, f"{BASE_URL}/{loc_slug}/"))
            loc_url = f"{BASE_URL}/{loc_slug}/"
            lines += _url_block(loc_url, _git_lastmod(f"{loc_slug}/index.html"), alts, priority='0.5', changefreq='monthly')

    lines.append('</urlset>')

    sitemap_path = os.path.join(out_dir, 'sitemap.xml')
    with open(sitemap_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'  sitemap.xml  ({sum(1 for l in lines if "<loc>" in l)} URLs, hreflang included)')


# ── Hash injection ────────────────────────────────────────────────────────────

def _inject_hashes(hashes, out_dir):
    """Replace __APP_HASH__, __WORKER_HASH__, __CSS_HASH__ placeholders in
    dist/sw.js and dist/js/processor.js, and append ?v=HASH to app.js script
    tags in all dist/**/*.html so the browser HTTP cache is busted on deploy."""
    targets = [
        os.path.join(out_dir, 'sw.js'),
        os.path.join(out_dir, 'js', 'processor.js'),
    ]
    replacements = {
        '__APP_HASH__':      hashes['app'],
        '__CACHE_VERSION__': hashes['cache_version'],
        '__WORKER_HASH__':   hashes['worker'],
        '__CSS_HASH__':      hashes['components_css'],
    }
    for path in targets:
        if not os.path.exists(path):
            print(f'  WARN: {path} not found, skipping injection')
            continue
        content = open(path, encoding='utf-8').read()
        for token, value in replacements.items():
            content = content.replace(token, value)
        with open(path, 'w', encoding='utf-8') as f:
            f.write(content)
    injected = [os.path.relpath(t, out_dir) for t in targets if os.path.exists(t)]
    print(f'  hash-injected: {injected}')

    # Inject version hash into every HTML file's app.js script tag.
    # Without this, Cache-Control: immutable on /js/* causes browsers to serve
    # the old app.js for up to a year even after a deployment.
    app_hash = hashes['app']
    html_count = 0
    for root, _dirs, files in os.walk(out_dir):
        for fname in files:
            if not fname.endswith('.html'):
                continue
            path = os.path.join(root, fname)
            content = open(path, encoding='utf-8').read()
            # Match all relative/absolute variants: ../js/app.js, js/app.js, /js/app.js
            new_content = content.replace(
                'app.js"', f'app.js?v={app_hash}"'
            )
            if new_content != content:
                with open(path, 'w', encoding='utf-8') as f:
                    f.write(new_content)
                html_count += 1
    print(f'  app.js?v={app_hash} injected into {html_count} HTML files')

    # Inject version hash into every HTML file's CSS <link> tags.
    # Without this, a CSS-only deploy leaves the browser cache serving stale
    # stylesheets even after the SW updates its cache version.
    css_hash = hashes['css']
    css_count = 0
    for root, _dirs, files in os.walk(out_dir):
        for fname in files:
            if not fname.endswith('.html'):
                continue
            path = os.path.join(root, fname)
            content = open(path, encoding='utf-8').read()
            new_content = re.sub(
                r'(href="[^"]*\.css)(?:\?v=[^"]*)?(")',
                rf'\g<1>?v={css_hash}\g<2>',
                content,
            )
            if new_content != content:
                with open(path, 'w', encoding='utf-8') as f:
                    f.write(new_content)
                css_count += 1
    print(f'  css?v={css_hash} injected into {css_count} HTML files')


# ── Static asset copy ─────────────────────────────────────────────────────────

def _should_skip(name, is_dir):
    if is_dir:
        return name in SKIP_DIRS
    if name in SKIP_FILES:
        return True
    _, ext = os.path.splitext(name)
    return ext in SKIP_EXTS


def _copy_static(src_root, dst_root, tool_dirs):
    """Copy everything from src_root to dst_root, skipping SSG-generated tool dirs."""
    copied = 0
    for entry in os.scandir(src_root):
        name = entry.name
        if name.startswith('.') and name not in {'.well-known'}:
            continue
        if _should_skip(name, entry.is_dir()):
            continue
        # Skip tool directories that will be generated
        if entry.is_dir() and name in tool_dirs:
            continue

        dst = os.path.join(dst_root, name)
        if entry.is_dir():
            # Deep copy directory, still skipping tool subdirs inside lang dirs
            _copy_dir_filtered(entry.path, dst, tool_dirs)
        else:
            os.makedirs(dst_root, exist_ok=True)
            shutil.copy2(entry.path, dst)
            copied += 1
    return copied


def _copy_dir_filtered(src, dst, tool_dirs):
    """Recursively copy a directory, skipping generated tool sub-dirs."""
    os.makedirs(dst, exist_ok=True)
    for entry in os.scandir(src):
        name = entry.name
        if name.startswith('.'):
            continue
        if _should_skip(name, entry.is_dir()):
            continue
        if entry.is_dir() and name in tool_dirs:
            continue
        dst_path = os.path.join(dst, name)
        if entry.is_dir():
            _copy_dir_filtered(entry.path, dst_path, tool_dirs)
        else:
            shutil.copy2(entry.path, dst_path)


# ── Tool page generation ──────────────────────────────────────────────────────

def _generate_pages(config, hashes, env, out_dir, dry_run=False):
    tmpl = env.get_template('tool-page.html')
    langs = config['languages']
    all_tools = config['tools']
    ui_all = config['ui']
    generated = 0

    for tool in all_tools:
        for lang, lang_cfg in langs.items():
            slug = tool['slugs'].get(lang)
            if not slug:
                continue

            if lang == 'en':
                canonical_path = f"{slug}/"
                prefix = '../'
            else:
                canonical_path = f"{lang_cfg['dir']}/{slug}/"
                prefix = '../../'

            seo_content, faq_items, howto_schema = _load_content(tool['id'], lang)
            hreflang = _hreflang_links(tool, config)

            html = tmpl.render(
                tool           = tool,
                lang           = lang,
                lang_cfg       = lang_cfg,
                prefix         = prefix,
                canonical_path = canonical_path,
                base_url       = BASE_URL,
                hreflang_links = hreflang,
                all_tools      = all_tools,
                nav_items      = _build_nav_items(lang, all_tools),
                ui             = ui_all[lang],
                seo_content    = seo_content,
                faq_items      = faq_items,
                webapp_schema  = _webapp_schema(tool, lang, canonical_path),
                faq_schema     = _faq_schema(faq_items) if faq_items else '',
                howto_schema   = howto_schema or '',
                breadcrumb_schema = _breadcrumb_schema(tool, lang, lang_cfg, canonical_path),
                hashes         = type('H', (), hashes)(),  # dict → attr access
                lang_names     = LANG_NAMES,
            )

            if not dry_run:
                if lang == 'en':
                    page_dir = os.path.join(out_dir, slug)
                else:
                    page_dir = os.path.join(out_dir, lang_cfg['dir'], slug)
                os.makedirs(page_dir, exist_ok=True)
                with open(os.path.join(page_dir, 'index.html'), 'w', encoding='utf-8') as f:
                    f.write(html)

            generated += 1

    return generated


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    dry_run = '--check' in sys.argv

    with open(CONFIG, encoding='utf-8') as f:
        config = json.load(f)

    # Build set of all tool directory names to skip during static copy
    tool_dirs = set()
    for tool in config['tools']:
        for lang, lang_cfg in config['languages'].items():
            slug = tool['slugs'].get(lang)
            if slug:
                tool_dirs.add(slug)

    hashes = _compute_hashes()
    print(f'Cache hashes: app={hashes["app"]}  worker={hashes["worker"]}  css={hashes["components_css"]}')

    env = Environment(
        loader=FileSystemLoader(TEMPLATES),
        autoescape=select_autoescape([]),  # HTML not auto-escaped — seo_content is trusted
        keep_trailing_newline=True,
    )

    if not dry_run:
        # Clean and recreate dist/
        if os.path.exists(DIST):
            shutil.rmtree(DIST)
        os.makedirs(DIST)

        # Copy static assets
        print('Copying static assets...')
        _copy_static(ROOT, DIST, tool_dirs)
        print('  done')

        # Inject computed hashes into sw.js and processor.js
        print('Injecting hashes...')
        _inject_hashes(hashes, DIST)

    # Generate tool pages
    print(f'Generating tool pages{"  (dry run)" if dry_run else ""}...')
    n = _generate_pages(config, hashes, env, DIST, dry_run)
    print(f'  {n} pages generated')

    if not dry_run:
        # Generate sitemap
        print('Writing sitemap...')
        _write_sitemap(config, DIST)

        # Write version manifest for production smoke testing
        print('Writing version manifest...')
        _write_version_json(hashes, DIST)

    print(f'\n{"DRY RUN OK" if dry_run else f"Build complete → dist/ ({n} tool pages)"}')


if __name__ == '__main__':
    main()
